
version: '3.7'
services:
    node:
        build: .
        ports:
        - "3000:3000" 
        depends_on:
          - db
        command:  bash -c "npx prisma migrate dev && npx prisma db seed && npm run dev"
    db:
      image: postgres
      environment:
        POSTGRES_USER: baylendoss
        POSTGRES_PASSWORD: baylendoss
        POSTGRES_DB: mydb
      ports:
      - "5432:5432"
    